spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  security:


jwt:
  issuer: Facilities-map-service
  secret_key: A2v4x8jJ6lP9zT3yQ1w4r7F2nK5b8mH0A2v4x8jJ6lP9zT3yQ1w4r7F2nK5b8mH0
